---
- name: run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: register variables
  ansible.builtin.import_tasks: variables.yml

- name: ensure i3 packages are installed [Debian]
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: ensure i3 packages are installed [Archlinux}
  ansible.builtin.include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: ensure i3 packages are installed [RHEL].
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'Fedora' or ansible_os_family == 'RedHat'

- name: create i3 config file
  ansible.builtin.include_tasks: config.yml
