---
- name: Run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versionchecki | bool

- name: Where to look
  ansible.builtin.debug:
    msg: "Have a look at https://galaxy.ansible.com/l3d/i3wm"

- name: Notify about Move
  ansible.builtin.fail:
    msg: "This Project moved to l3d.i3wm"
