---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  when:
    - ansible_pkg_mgr == "apt"

- name: Ensure i3 packages are installed.
  ansible.builtin.apt:
    name: "{{ i3_packages }}"
    state: "present"
  become: true
